### ISSUE TITLE
Looking good my man :)

### ISSUE THREAD

**Issue by Mccranky83** [XinghaiGe/Notes#1]

**Comment by XinghaiGe** [comment]
And, do not always provided no description.

**Comment by Mccranky83** [comment]
It's "demonstration".

**Comment by XinghaiGe** [comment]
![Screenshot_20240506_165352_com.github.android_edit_6633369292737.jpg](https://github.com/XinghaiGe/Notes/assets/55051367/3d07fd36-eb88-40c1-b760-924dc3ee45d3)

I say this.

**Comment by XinghaiGe** [comment]
Ok, u can pr to fix it.
